-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("plugins.toggleterm")
require("plugins.swear-cursor")
require("plugins.nvim-surround")
--require("plugins.smoother")
--require("plugins.avante")
--require("plugins.codecompanion")
require("plugins.mini-diff")
require("plugins.render-markdown")